name: AutoList

on:
  schedule:
    - cron: '0 0 * * *' # 自动运行早上8点
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: ubuntu-22.04@20240422.1.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        #run: pip install selenium==4.19.0 requests==2.31.0 futures==3.0.5 eventlet==0.36.1
        run: pip install selenium requests futures eventlet aiohttp aiofiles

      #- name: Run itv_all
        #run: python ${{ github.workspace }}/itv_all.py

      - name: Run new
        run: python ${{ github.workspace }}/new.py
        
      #- name: Run weishi
        #run: python ${{ github.workspace }}/weishi.py
        
      #- name: Run qita
        #run: python ${{ github.workspace }}/qita.py
        
      - name: 提交更改
        run: |
          git config --local user.email "65896321456@qq.com"
          git config --local user.name "65896321456"
          git add .
          git commit *.txt -m "Add generated file"
          git commit *.m3u -m "Add generated file"
          #git pull --rebase
          git push -f
